### ISSUE TITLE
Resource failing with "fatal: not in a git directory" when configured with "skip_ssl_verification: true"

### ISSUE THREAD

**Issue by gid0** [concourse/semver-resource#106]
Hello,

Our users were using this kind of resource definition with the v1.0.2 release :

```yaml
- name: app-version
  source:
    branch: master
    depth: 1
    driver: git
    file: apps/service/develop
    initial_version: 1.0.0
    private_key: ((ssh_key.private_key))
    skip_ssl_verification: true
    uri: ssh://git@local-git-server:7999/project/repo.git
  type: semver
```

When we switched to the v1.1.1 release of the resource type with Concourse 5.7.0, we started seeing this kind of failure on all the semver resources :

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
From ssh://local-git-server:7999/project/repo
 * branch            master     -> FETCH_HEAD
HEAD is now at 968d7e4 bump to 1.0.0-develop.21
fatal: not in a git directory
error checking for new versions: exit status 128
```

I tracked the culprit to be "skip_ssl_verification: true" : by removing it from the resource source, resources start working again.

I know that this flag has no meaning when using git over ssh but the resources were previously working with v1.0.2. I tried with v1.1.0 and they were failing too. This flag should be ignored when using git over ssh.
