### ISSUE TITLE
GCS Semver File Does not seem to be updating

### ISSUE THREAD

**Issue by xtreme-shane-lattanzio** [concourse/semver-resource#112]
In a pipeline that I am simply trying to bump a semver file. If the resource is

```
- name: semver-version
  type: semver
  source:
    driver: gcs
    bucket: lf-semver-version
    key: VERSION
    json_key: ((GCPQueuedReportsBucketCredentials))
```

and the usage is

```
- name: bump-minor
  plan:
    - put: semver-version
      tags: ["private-worker"]
      params: {bump: minor}
```

Why is it getting the file correctly and then putting the exact same file without bumping?? This screenshot is with 6.2.0 in the bucket:

![Screen Shot 2020-05-22 at 12 16 30 PM](https://user-images.githubusercontent.com/5375096/82702136-74857f00-9c3f-11ea-9545-69ec5239cacd.png)

Basically it is bumping the version but not in the GCP file at all and returning the same version. I can get it to bump in concourse using the same version file when I change it to
```
- name: bump-minor
  plan:
    - get: semver-version
      tags: ["private-worker"]
      params: {bump: minor}
    - put: semver-version
      params: {file: semver-version/version}
```

But in that way the actual file still doesn't update you just get:

![Screen Shot 2020-05-22 at 12 17 43 PM](https://user-images.githubusercontent.com/5375096/82702174-81a26e00-9c3f-11ea-8f30-530c8c454238.png)

Any idea why the GCS file is not updating? With the get/put flow, it at least bumps the version in concourse metadata but the atomic put flow doesn't seem to work at all. HALP!!
