### ISSUE TITLE
error bumping version: private keys with passphrases are not supported

### ISSUE THREAD

**Issue by CalamarBicefalo** [concourse/semver-resource#115]
I have a pair of credentials that are not passphrase protected. The key has read/write access in GitHub.

For the current pipeline:
```yaml
jobs:
  - name: test-and-build
    plan:
      - get: a-service
        trigger: true
      - put: version
        params:
          pre: SNAPSHOT
```

and the following resources:
```yaml
resources:
  - name: a-service
    type: git
    source:
      uri: git@github.com:org/a-service.git
      branch: master
      private_key: ((a-service-deploy-key))

  - name: version
    type: semver
    source:
      initial_version: "0.0.0"
      driver: git
      uri: git@github.com:org/versions.git
      private_key: ((versions-deploy-key))
      branch: master
      file: a-service
```

I get the error:
`error bumping version: private keys with passphrases are not supported`

I saw a [similar report](https://github.com/concourse/git-resource/issues/88) in the git resource and followed advice there... **The interesting thing is that if I use the version repo as input for the git resource, the git resource is capable of fetching the latest version commit (and then the version resource complains even though it is using the very same key/url)**, which proves:
- The key is correct and works
- The key is properly interpolated
- Other git backed concourse resources seem happy with that

Any thoughts?

**Comment by CalamarBicefalo** [comment]
I found the problem... but it may be something nice to address in the resource.

It was indeed a key finishing without the new blank line. The bad news is that we use AWS secret manager and it seems to strip blank lines no matter what...

Adding any arbitrary new line would make it work but it is not a scalable solution.

**Comment by CalamarBicefalo** [comment]
For anyone interested, a cleaner workaround in case you cannot add a blank line to the key (that was our case) would be:
```yaml
  - name: version
    type: semver
    source:
      initial_version: "0.0.0"
      driver: git
      uri: git@github.com:org/versions.git
      private_key: |
         ((versions-deploy-key))
      branch: master
      file: a-service
```
