### ISSUE TITLE
[Question] How to use bumped version in image tag file? (as opposed to version when the job started)

### ISSUE THREAD

**Issue by jewbetcha** [concourse/semver-resource#120]
We're using semver to bump versions of our project, the version file is then used as the tag for our image outputs. Config is pretty standard:
```
resources:
- name: version
    type: semver
    source:
      driver: git
      branch: master
      uri: repo.git
      file: path/to/version

jobs:
  - name: build
    plan:
      - get: version
        params:
          bump: minor
  - get: repo
     trigger: true
   ...
  - put: version
     params:
        bump: minor
  - inputs:
        - repo
        - assets
        - version
      params:
          build: assets
          tag_file: path/to/version
        put: image
```
(sorry for bad YAML formatting!)

As it stands, the version bumps correctly and commits the change, however the tag file for the image is always the version that the repo contained when the job started.

i.e. job starts with v 0.0.1 -> bumps to 0.0.2 -> commits 0.0.2 -> image pushed with 0.0.1

Is there a way for concourse to use the _new_ bumped version for the tag file?

Thank you!
