### ISSUE TITLE
s3 put with file params does not entertain bump field

### ISSUE THREAD

**Issue by subhash12** [concourse/semver-resource#127]
The README mentions about atomic put, where version can be bumped up during put action.

When it has file param, then the bump does not seem to happen
```
- put: version
  params:
     bump: minor
     file: version/version
```
Is there any plans to support both file and bump params attributes
