### ISSUE TITLE
Swift properties requiring the openstack key is not documented

### ISSUE THREAD

**Issue by Samze** [concourse/semver-resource#13]
It is not documented that using semver with the swift driver requires the use of the `openstack` key.

This does not work. 
```
- name: version
  type: semver
  source:
    driver: swift
    container: bgd-version
    item_name: version
    region: dallas
    ...
```
Whereas this does:

```
- name: version
  type: semver
  source:
    driver: swift
    openstack:
      container: bgd-version
      item_name: version
      region: dallas
      ...
```
