### ISSUE TITLE
%version% in commit message is not getting substituted  

### ISSUE THREAD

**Issue by mankel08** [concourse/semver-resource#133]
Hi, 

We are using semver-resource v1.4.0. We have defined the resource as follows.

```
- name: dev-semver
  type: semver
  icon: pound-box
  source:
    driver: git
    uri: <some-git-repo>
    branch: master
    commit_message: "semver bump to %version%"
    file: <some-path>/dev
```
We do a `put: dev-semver`. The expectation is that value in a file `<some-path>/dev` would get updated with a commit message _`semver bump to 1.0.1`_ . This works perfectly fine when the resource does not do/need a rebase of the git repo. 

However, when the `put: dev-semver` does an automatic rebase before pushing; the `%version%` is not substituted and remains as %version% in the commit message.
Ex: _`semver bump to %version%`_
