### ISSUE TITLE
Put semver silently ignoring error

### ISSUE THREAD

**Issue by georgethebeatle** [concourse/semver-resource#33]
We have a bump major version job like this:

```
  - name: garden-runc-bump-major-version
    serial: true
    plan:
    - get: gr-version
      params: {bump: major, pre: rc}
    - put: gr-version
      params: {file: gr-version/number}
```

It looks like when it was last ran the version` 1.2.1-rc.42` was fetched and locally bumped to `1.3.0-rc.1` but we checked the backing s3 file and it was containing `1.2.2-rc.3` which means that most probably the `1.3.0-rc.1` version failed to be pushed back to s3 and the error was silently ignored by semver resource.

Here is a screenshot:
![pasted image at 2017_03_13 10_29 am](https://cloud.githubusercontent.com/assets/9860469/23861956/5afb1be8-0814-11e7-80bc-52f8d715a82b.png)
