### ISSUE TITLE
Infinite Loop when Git Permission Denied

### ISSUE THREAD

**Issue by danger-ranger** [concourse/semver-resource#38]
https://media.giphy.com/media/fExunDejohBMQ/giphy.gif

**Comment by xtreme-gavin-enns** [comment]
```
Please make sure you have the correct access rights
and the repository exists.
From github.com:pivotal-cf/s3-image-resource
 * branch            master     -> FETCH_HEAD
HEAD is now at 8069372 adds test tag name file
ERROR: Permission to pivotal-cf/s3-image-resource.git denied to concourse-olm-bot.
fatal: Could not read from remote repository.
```

**Comment by RaniSputnik** [comment]
We are also seeing this same issue, but we get no error message.

```
From github.com:Organisation/Repository
 * branch            develop    -> FETCH_HEAD
HEAD is now at 5732f88 Add versions directory (#22)
From github.com:Organisation/Repository
 * branch            develop    -> FETCH_HEAD
HEAD is now at 5732f88 Add versions directory (#22)
From github.com:Organisation/Repository
 * branch            develop    -> FETCH_HEAD
HEAD is now at 5732f88 Add versions directory (#22)
From github.com:Organisation/Repository
 * branch            develop    -> FETCH_HEAD
```
I think I've found the issue in the git driver.

This code assumes that an error will be returned OR a write will occurr. If neither of those two things happens, the loop is never broken. https://github.com/concourse/semver-resource/blob/0cb9fc02fa50ba780c9a3611323eeaeb6ceee020/driver/git.go#L93-L107

When calling `setupRepo` we occassionally return no error and no write https://github.com/concourse/semver-resource/blob/0cb9fc02fa50ba780c9a3611323eeaeb6ceee020/driver/git.go#L339-L349

I think this is incorrect, we should probably return an error for each of the three cases above.

**Comment by RaniSputnik** [comment]
This is what our plan looks like;
```
 - name: assign-version-image
    plan:
      - aggregate:
        - get: source
          resource: git-develop
          trigger: true
          passed: [run-tests]
        - get: image-version-temp
        - get: image-version-dev
          params:
            bump: patch

        attempts: ((attempts))
        timeout: ((timeout))

      - put: image-version-temp
        params:
          file: image-version-dev/number
```
In our case the failure is occurring in the `put: image-version-temp` step.

**Comment by renbeynolds** [comment]
We are seeing the same behavior as well:

Concourse Version: 4.2.1

Config:
```yaml
- name: version
  type: semver
  source:
    driver: git
    uri: ((versions_repo))
    branch: master
    file: ((version_path))
    private_key: ((aoc_gitlab.private_key))

- name: release-patch
  plan:
  - aggregate:
    - get: snapshot
      passed: [deploy-acceptance]
    - get: version
      params:
        bump: patch
    - get: pipeline-repo
    - get: release-repo
  - task: replace hash with version
    file: pipeline-repo/tasks/replace-hash-version.yml
  - put: release
    params:
      file: updated-snapshot/*
      version_file: version/version
  - put: version
    params: { file: version/version }
```

Log:
```
Cloning into '/tmp/semver-git-repo'...
Warning: Permanently added 'git.aoc-pathfinder.cloud,160.1.51.126' (ECDSA) to the list of known hosts.
HEAD is now at 2e88ca1 bump to 0.37.0
From git.aoc-pathfinder.cloud:dev-enablement/product-versions
 * branch            master     -> FETCH_HEAD
HEAD is now at 2e88ca1 bump to 0.37.0
From git.aoc-pathfinder.cloud:dev-enablement/product-versions
 * branch            master     -> FETCH_HEAD
HEAD is now at 2e88ca1 bump to 0.37.0
From git.aoc-pathfinder.cloud:dev-enablement/product-versions
 * branch            master     -> FETCH_HEAD
HEAD is now at 2e88ca1 bump to 0.37.0
From git.aoc-pathfinder.cloud:dev-enablement/product-versions
 * branch            master     -> FETCH_HEAD
HEAD is now at 2e88ca1 bump to 0.37.0
From git.aoc-pathfinder.cloud:dev-enablement/product-versions
 * branch            master     -> FETCH_HEAD
HEAD is now at 2e88ca1 bump to 0.37.0
From git.aoc-pathfinder.cloud:dev-enablement/product-versions
 * branch            master     -> FETCH_HEAD
HEAD is now at 2e88ca1 bump to 0.37.0
From git.aoc-pathfinder.cloud:dev-enablement/product-versions
 * branch            master     -> FETCH_HEAD
HEAD is now at 2e88ca1 bump to 0.37.0
```
