### ISSUE TITLE
Getting `no version bump specified` when bumping the patch on get

### ISSUE THREAD

**Issue by myles-mcdonnell** [concourse/semver-resource#63]
I have configured our build like this:

```
- get: version
    params: {bump: patch}
  - task: "our_build_task"
       <redacted>
  - put: version

- name: version
  type: semver
  source:
    initial_version: 0.0.0
    driver: git
    uri: git@github.com:<redacted>.git
    branch: master
    private_key: ((github_private_key))
    file: version
```

Which results in ***no version bump specified*** when the put executes.    My expectation is that it would bump the version file locally before running the build then put that version.  We are running concourse 3.9.2...I just noticed 3.10.0 is available, would an upgrade fix this? and/or should we pull in the semver recourse type rather than use the integrated version?
