### ISSUE TITLE
tag always tags head, it should tag the revision in the `get`

### ISSUE THREAD

**Issue by ghostsquad** [concourse/semver-resource#72]
When tagging, it always tags HEAD, instead of the revision pulled with `get`. This makes it impossible to do something like:

```yaml
jobs:
- name: first
  steps:
  - get: source
  - task: <build>
- name: second
  steps:
  - get: source
    passed: [first]
  - put: source
    params:
      tag: foo
      only_tag: true
```
