### ISSUE TITLE
version marked invalid still used and bumped incorrectly

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/semver-resource#73]
Concourse 4.0.0

I marked a version as 'invalid', then proceeded to bump it.

The version it 'gets' is `0.0.0`, yet it bumps it to `0.1.1` meaning it started from the 'bad' version. Seems like it's improperly using the cache or something.

```
- name: bump-patch
  serial_groups:
  - version
  plan:
  - get: version
  - put: version
    params:
      bump: patch
```

<img width="1439" alt="screen shot 2018-08-07 at 2 19 04 pm" src="https://user-images.githubusercontent.com/34585329/43797457-16f89a70-9a4d-11e8-906a-97d4748f9943.png">

<img width="559" alt="screen shot 2018-08-07 at 2 19 28 pm" src="https://user-images.githubusercontent.com/34585329/43797463-1ccb22b0-9a4d-11e8-86f3-c9289e1dd146.png">

I thought maybe it was an 'atomic put' issue cause I was doing an unnecessary get, I think?

So I removed the `  - get: version` line from `bump-patch` and tried marking the latest version as invalid again, and then 'bumping' it, and it still just immediately bumped to `0.1.2`, again ignoring the fact that `0.1.1` was marked as 'bad' and the only remaining good version is `0.0.0`

(I didn't grab a screenshot before it made `0.1.2`, but you can see that `0.0.0` should have been the only valid version)

<img width="446" alt="screen shot 2018-08-07 at 2 27 17 pm" src="https://user-images.githubusercontent.com/34585329/43797761-17dd15fa-9a4e-11e8-9639-d0099aff8f86.png">

**Comment by eedwards-sk** [comment]
Okay, I'll leave this up for posterity, but I just now realized why this is happening...


I'm storing the version in a file, so the file version value itself never reverts when I mark a version as invalid. I guess I was thinking about the flow of versioning incorrectly here.

Being able to mark a version as 'bad' and go back still seems like something missing though.

**Comment by eedwards-sk** [comment]
I found a workaround for this I called `repair-version`, as if you issue an explicit `get` followed by an explicit `put` you can get and put the actual 'latest version' which then makes the version file reflect the actual version you want it to.

```
- name: repair-version
  serial_groups:
  - version
  plan:
  - get: version
  - put: version
    params:
      file: version/version
```

after running this I was able to then `bump-patch` and get a new valid version to start from

<img width="553" alt="screen shot 2018-08-07 at 2 39 34 pm" src="https://user-images.githubusercontent.com/34585329/43798297-c53edb9c-9a4f-11e8-83c6-9ebdbd2e7b82.png">
