### ISSUE TITLE
No such device or address error in semver and git resources.

### ISSUE THREAD

**Issue by larssb** [concourse/semver-resource#80]
I get this error:

```txt
resource script '/opt/resource/check []' failed: exit status 1

stderr:
Cloning into '/tmp/semver-git-repo'...
fatal: could not read Username for 'https://bengtssondd.it': No such device or address
error checking for new versions: exit status 128`
```

On my:
- MacOS v10.13.6
- Docker v18.06.1-ce-mac73
- Docker compose v1.22
- Concourse CI v4.2.1

The config for semver in my pipeline YAML is:
```yml
- name: version
  type: semver
  source:
    branch: version
    driver: git
    file: version
    initial_version: 1.2.1
    password: ((myuser_pass))
    uri: https://bengtssondd.it/git/healops.git
    username: myuser
```

I have tried:
- Downgradring to v3.10 of ConourseCI where it used to work. Now it doesn't
- Thinking about what I've changed:
-- Using a docker-compose v3.2 file
-- Postgres v10.5
- I tried again on another Macbook I have. And no error. It works. But why in the world. It do have a newer version of Git installed. But is that really it? Does the semver and git resources really use the local version of Git? What is going on here? Would be great to get a clearer view on this issue. Thank you.
- Tried updating Git on the non-working Mac. Even did a full Docker restart on MacOS. And a full re-install of ConcourseCI, removed the Postgres volume.

N.B. 2FA is not enabled on the Git setup I'm using.

----

What in the world could be wrong?
