### ISSUE TITLE
If git fails to push, it will not stop retrying

### ISSUE THREAD

**Issue by dimaj** [concourse/semver-resource#89]
Had a situation, where the user that was pushing to our git repo didn't have push rights to a restricted branch. As a result, the step was running over and over again. There was no helpful information as to what was happening.

I think it would be nice if errors from git were surfaced to the logs and retry had a limit.

**Comment by Gregro** [comment]
What do you mean that "the step was running over and over again"?   In our case, Concourse doesn't have permission to write to `develop` where `src/version.txt` is.    

However, the `put` step lights up green.  Also, the version number keeps incrementing in subsequent jobs -- I assume this gets cached in the resource?

Since we have no idea the `git push` failures are happening, if something ever wipes the state in Concourse, our version number would get reset.

Configuration (Concourse v 5.7.0) is:
```yaml
resources:
- name: library-version
  type: semver
  source:
    branch: develop
    driver: git
    file: src/version.txt
    private_key: ((bitbucket-repo-private-key))
    uri: ssh://git@domain:1234/project/repo.git

jobs:
- name: job-build-packages
  serial: true
  plan:
  - get: library-version
    params:
      bump: patch
  - put: library-version
    params:
      file: library-version/version
```

Output of `put` step:
```
Cloning into '/tmp/semver-git-repo'...
Warning: Permanently added '[domain]:1234,[127.0.0.1]:1234' (RSA) to the list of known hosts.
HEAD is now at abcd987 latest-commit-message-here
From ssh://domain:1234/project/repo
 * branch            develop    -> FETCH_HEAD
HEAD is now at abcd987 latest-commit-message-here
From ssh://domain:1234/project/repo
 * branch            develop    -> FETCH_HEAD
HEAD is now at abcd987 latest-commit-message-here
```

The contents of `src/version.txt` remain at `1.3.0`, but subsequent runs of the pipeline have this in the `get: library-version` step:
`bumped locally from 1.3.5 to 1.3.6`
`bumped locally from 1.3.6 to 1.3.7`
