### ISSUE TITLE
pre does not seem to like prefix, unsure why

### ISSUE THREAD

**Issue by ccrvincent** [concourse/semver-resource#91]
Config:

```
resources:
[...]
  - name: version
    type: semver
    source:
      initial_version: 0.0.0-pr.((pr-name)).0
      driver: git
      branch: pipeline-state
      file: ((pr-name)).version
      uri: https://bitbucket/scm/prj/repo.git
[...]
  - name: increment-pr
    serial_groups: [version]
    plan:
    - aggregate:
      - get: source
        trigger: true
      - get: version
        params: {pre: pr.((pr-name))}
    - put: source
      params:
        repository: source
    - put: version
      params: {file: version/number}
```

When the increment-pr task runs, I get the same output as the input:
`bumped locally from 1.1.2-pr.project-pr-chad-pipeline-test.1 to 1.1.2-pr.project-pr-chad-pipeline-test.1`

Any idea why the patch isn't bumping?  Does it not like/allow a period?
`The value of pre can be anything you like; the value will be pre-pended (hah) to a numeric value.`
